import re

inputFile = input('Enter filename here: ')
outputFile = 'output_' + inputFile

# open file
f = open(inputFile,'r')
newData = f.read()
f.close()

# functions
def fixEmptyVerse(text):
    # first fix books with chapter 1 ONLY
    # oneChapterBook = [31,57,63,64,65,72,73,75,79,85]
    fixedText = text
    fixedText = re.sub('<ref onclick="bcv\((31|57|63|64|65|72|73|75|79|85),([0-9]+?),\)">', r'<ref onclick="bcv(\1,1,\2)">', fixedText)
    fixedText = re.sub('<ref onclick="bcv\(([0-9]+?),([0-9]+?),\)">', r'<ref onclick="bcv(\1,\2,1)">＊', fixedText)
    return fixedText

def standardReference(text, answer):
    fixedText = text
    if answer == 'YES':
        fixedText = re.sub('<ref onclick="bcv\(1,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(1,\1,\2)">Gen \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(2,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(2,\1,\2)">Exod \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(3,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(3,\1,\2)">Lev \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(4,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(4,\1,\2)">Num \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(5,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(5,\1,\2)">Deut \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(6,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(6,\1,\2)">Josh \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(7,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(7,\1,\2)">Judg \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(8,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(8,\1,\2)">Ruth \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(9,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(9,\1,\2)">1Sam \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(10,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(10,\1,\2)">2Sam \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(11,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(11,\1,\2)">1Kgs \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(12,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(12,\1,\2)">2Kgs \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(13,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(13,\1,\2)">1Chr \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(14,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(14,\1,\2)">2Chr \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(15,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(15,\1,\2)">Ezra \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(16,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(16,\1,\2)">Neh \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(17,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(17,\1,\2)">Esth \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(18,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(18,\1,\2)">Job \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(19,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(19,\1,\2)">Ps \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(20,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(20,\1,\2)">Prov \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(21,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(21,\1,\2)">Eccl \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(22,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(22,\1,\2)">Song \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(23,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(23,\1,\2)">Isa \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(24,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(24,\1,\2)">Jer \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(25,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(25,\1,\2)">Lam \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(26,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(26,\1,\2)">Ezek \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(27,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(27,\1,\2)">Dan \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(28,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(28,\1,\2)">Hos \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(29,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(29,\1,\2)">Joel \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(30,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(30,\1,\2)">Amos \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(31,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(31,\1,\2)">Obad \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(32,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(32,\1,\2)">Jonah \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(33,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(33,\1,\2)">Mic \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(34,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(34,\1,\2)">Nah \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(35,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(35,\1,\2)">Hab \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(36,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(36,\1,\2)">Zeph \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(37,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(37,\1,\2)">Hag \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(38,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(38,\1,\2)">Zech \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(39,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(39,\1,\2)">Mal \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(40,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(40,\1,\2)">Matt \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(41,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(41,\1,\2)">Mark \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(42,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(42,\1,\2)">Luke \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(43,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(43,\1,\2)">John \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(44,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(44,\1,\2)">Acts \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(45,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(45,\1,\2)">Rom \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(46,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(46,\1,\2)">1Cor \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(47,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(47,\1,\2)">2Cor \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(48,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(48,\1,\2)">Gal \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(49,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(49,\1,\2)">Eph \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(50,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(50,\1,\2)">Phil \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(51,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(51,\1,\2)">Col \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(52,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(52,\1,\2)">1Thess \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(53,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(53,\1,\2)">2Thess \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(54,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(54,\1,\2)">1Tim \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(55,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(55,\1,\2)">2Tim \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(56,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(56,\1,\2)">Titus \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(57,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(57,\1,\2)">Phlm \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(58,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(58,\1,\2)">Heb \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(59,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(59,\1,\2)">Jas \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(60,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(60,\1,\2)">1Pet \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(61,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(61,\1,\2)">2Pet \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(62,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(62,\1,\2)">1John \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(63,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(63,\1,\2)">2John \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(64,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(64,\1,\2)">3John \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(65,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(65,\1,\2)">Jude \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(66,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(66,\1,\2)">Rev \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(70,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(70,\1,\2)">Bar \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(71,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(71,\1,\2)">AddDan \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(72,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(72,\1,\2)">PrAzar \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(73,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(73,\1,\2)">Bel \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(75,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(75,\1,\2)">Sus \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(76,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(76,\1,\2)">1Esd \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(77,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(77,\1,\2)">2Esd \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(78,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(78,\1,\2)">AddEsth \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(79,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(79,\1,\2)">EpJer \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(80,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(80,\1,\2)">Jdt \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(81,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(81,\1,\2)">1Macc \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(82,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(82,\1,\2)">2Macc \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(83,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(83,\1,\2)">3Macc \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(84,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(84,\1,\2)">4Macc \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(85,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(85,\1,\2)">PrMan \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(86,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(86,\1,\2)">Ps151 \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(87,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(87,\1,\2)">Sir \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(88,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(88,\1,\2)">Tob \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(89,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(89,\1,\2)">Wis \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(90,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(90,\1,\2)">PssSol \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(91,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(91,\1,\2)">Odes \1:\2</ref>', fixedText)
        fixedText = re.sub('<ref onclick="bcv\(92,([0-9]+?),([0-9]+?)\)">.*?</ref>', r'<ref onclick="bcv(92,\1,\2)">EpLao \1:\2</ref>', fixedText)
        print("All verse references had been standardised.")
    else:
        print("Verse references are NOT standardised.")
    return fixedText

# locate where books
newData = re.sub('(The Song of the Three Holy Children) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Song of the Three Holy Children) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Epistle to the Laodiceans) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(The Song of Three Youths) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Song of Three Children) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(The Song of Three Jews) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Canticle of Canticles) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(Epistle to Laodiceans) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(Second Thessalonians) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(Song of Three Youths) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(First Thessalonians) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(Additions to Daniel) ([0-9])', r'『71｜\1』 \2', newData)
newData = re.sub('(Additions to Esther) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(Second Corinthians) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(Apocalypse of John) ([0-9])', r'『66｜\1』 \2', newData)
newData = re.sub('(Revelation to John) ([0-9])', r'『66｜\1』 \2', newData)
newData = re.sub('(Bel and the Dragon) ([0-9])', r'『73｜\1』 \2', newData)
newData = re.sub('(Song of Three Jews) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(The Rest of Esther) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(Letter of Jeremiah) ([0-9])', r'『79｜\1』 \2', newData)
newData = re.sub('(Prayer of Manasseh) ([0-9])', r'『85｜\1』 \2', newData)
newData = re.sub('(Prayer of Manasses) ([0-9])', r'『85｜\1』 \2', newData)
newData = re.sub('(Epistle Laodiceans) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(Second Chronicles) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(First Corinthians) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(1st Thessalonians) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2nd Thessalonians) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(Prayer of Azariah) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Prayer of Azariah) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Wisdom of Solomon) ([0-9])', r'『89｜\1』 \2', newData)
newData = re.sub('(Psalms of Solomon) ([0-9])', r'『90｜\1』 \2', newData)
newData = re.sub('(Epist[\.]*? Laodiceans) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(First Chronicles) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Thessalonians) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(Sg[\.]*? of 3 Childr[\.]*?) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Second Maccabees) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(Fourth Maccabees) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Additional Psalm) ([0-9])', r'『86｜\1』 \2', newData)
newData = re.sub('(Song of Solomon) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(1st Corinthians) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(2nd Corinthians) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Thessalonians) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Thessalonians) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Thessalonians) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(First Maccabees) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(Third Maccabees) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(1st Chronicles) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2nd Chronicles) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Corinthians) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(1Thessalonians) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2Thessalonians) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(Second Timothy) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(The Revelation) ([0-9])', r'『66｜\1』 \2', newData)
newData = re.sub('(Rest of Esther) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(Ecclesiasticus) ([0-9])', r'『87｜\1』 \2', newData)
newData = re.sub('(Psalms Solomon) ([0-9])', r'『90｜\1』 \2', newData)
newData = re.sub('(Second Samuel) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(Second Chron[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Song of Songs) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Corinthians) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Corinthians) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Corinthians) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(Second Thess[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(First Timothy) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(Song of Three) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Second Esdras) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(1st Maccabees) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2nd Maccabees) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3rd Maccabees) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Maccabees) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4th Maccabees) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Wisd[\.]*? of Sol[\.]*?) ([0-9])', r'『89｜\1』 \2', newData)
newData = re.sub('(First Samuel) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(Second Kings) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Chronicles) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(First Chron[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Chronicles) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Ecclesiastes) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(Lamentations) ([0-9])', r'『25｜\1』 \2', newData)
newData = re.sub('(1Corinthians) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(2Corinthians) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(First Thess[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(Second Peter) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(Song of Thr[\.]*?) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(First Esdras) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Maccabees) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(IV[ ]*?Maccabees) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Deuteronomy) ([0-9])', r'『5｜\1』 \2', newData)
newData = re.sub('(Second Sam[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(First Kings) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(Second Kgs[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(Philippians) ([0-9])', r'『50｜\1』 \2', newData)
newData = re.sub('(1st Timothy) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(2nd Timothy) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(Second Tim[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(First Peter) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(Second John) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(Bel and Dr[\.]*?) ([0-9])', r'『73｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Maccabees) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Maccabees) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Maccabees) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3[ ]*?Maccabees) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4[ ]*?Maccabees) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Pr[\.]*? of Man[\.]*?) ([0-9])', r'『85｜\1』 \2', newData)
newData = re.sub('(Ps[\.]*? Solomon) ([0-9])', r'『90｜\1』 \2', newData)
newData = re.sub('(1st Samuel) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(First Sam[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(2nd Samuel) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(First Kgs[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(1st Chron[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2nd Chron[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Colossians) ([0-9])', r'『51｜\1』 \2', newData)
newData = re.sub('(1st Thess[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2nd Thess[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(First Tim[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Timothy) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(First John) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(Third John) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(Revelation) ([0-9])', r'『66｜\1』 \2', newData)
newData = re.sub('(1st Esdras) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(2nd Esdras) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(Add[\.]*? Esth[\.]*?) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(1Maccabees) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2Maccabees) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3Maccabees) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4Maccabees) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Add[\.]*? Psalm) ([0-9])', r'『86｜\1』 \2', newData)
newData = re.sub('(Laodiceans) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(Leviticus) ([0-9])', r'『3｜\1』 \2', newData)
newData = re.sub('(1st Kings) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2nd Kings) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Chron[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Canticles) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(Zephaniah) ([0-9])', r'『36｜\1』 \2', newData)
newData = re.sub('(Zechariah) ([0-9])', r'『38｜\1』 \2', newData)
newData = re.sub('(Galatians) ([0-9])', r'『48｜\1』 \2', newData)
newData = re.sub('(Ephesians) ([0-9])', r'『49｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Thess[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Timothy) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Timothy) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Timothy) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(1st Peter) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(2nd Peter) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(Add[\.]*? Dan[\.]*?) ([0-9])', r'『71｜\1』 \2', newData)
newData = re.sub('(Pr[\.]*? Azar[\.]*?) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Sg[\.]*? Three) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Song Thr[\.]*?) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Esdras) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(Let[\.]*? Jer[\.]*?) ([0-9])', r'『79｜\1』 \2', newData)
newData = re.sub('(Ltr[\.]*? Jer[\.]*?) ([0-9])', r'『79｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Macc[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(Ep[\.]*? Laod[\.]*?) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Samuel) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(1st Sam[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Samuel) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(2nd Sam[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(1st Kgs[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2nd Kgs[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Chron[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Chron[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Chron[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Nehemiah) ([0-9])', r'『16｜\1』 \2', newData)
newData = re.sub('(Proverbs) ([0-9])', r'『20｜\1』 \2', newData)
newData = re.sub('(Jeremiah) ([0-9])', r'『24｜\1』 \2', newData)
newData = re.sub('(Habakkuk) ([0-9])', r'『35｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Thess[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Thess[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Thess[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Thes[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(1Timothy) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(1st Tim[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(2Timothy) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(2nd Tim[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(Philemon) ([0-9])', r'『57｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Peter) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(1st John) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(2nd John) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(3rd John) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Jhn[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Joh[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(III[ ]*?John) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Esdras) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(1Esdras[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Esdras) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Esdras) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Esdr[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(Add[\.]*? Es[\.]*?) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(AddEsth[\.]*?) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(Ep[\.]*? Jer[\.]*?) ([0-9])', r'『79｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Macc[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Mac[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(IV[ ]*?Macc[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Add[\.]*? Ps[\.]*?) ([0-9])', r'『86｜\1』 \2', newData)
newData = re.sub('(Ps[\.]*? Sol[\.]*?) ([0-9])', r'『90｜\1』 \2', newData)
newData = re.sub('(Ep[\.]*? Lao[\.]*?) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(Genesis) ([0-9])', r'『1｜\1』 \2', newData)
newData = re.sub('(Numbers) ([0-9])', r'『4｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Sam[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Kings) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Kings) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Kgs[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(1Chron[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2Chron[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Chr[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Eccles[\.]*?) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(Ezekiel) ([0-9])', r'『26｜\1』 \2', newData)
newData = re.sub('(Obadiah) ([0-9])', r'『31｜\1』 \2', newData)
newData = re.sub('(Malachi) ([0-9])', r'『39｜\1』 \2', newData)
newData = re.sub('(Matthew) ([0-9])', r'『40｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Cor[\.]*?) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(Philip[\.]*?) ([0-9])', r'『50｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Thes[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(1Thess[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Thes[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Thes[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(2Thess[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Tim[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(Philem[\.]*?) ([0-9])', r'『57｜\1』 \2', newData)
newData = re.sub('(Hebrews) ([0-9])', r'『58｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Peter) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Peter) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Peter) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Pet[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Jhn[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Joh[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(II[ ]*?John) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Jn[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Jo[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(AddDan[\.]*?) ([0-9])', r'『71｜\1』 \2', newData)
newData = re.sub('(PrAzar[\.]*?) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Azariah) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Pr[\.]*? Az[\.]*?) ([0-9])', r'『72｜\1』 \2', newData)
newData = re.sub('(Susanna) ([0-9])', r'『75｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Esdr[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Esdr[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Esdr[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(2Esdras) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Esd[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Macc[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Macc[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Macc[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Mac[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3[ ]*?Macc[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(III[ ]*?Ma[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4[ ]*?Macc[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(IV[ ]*?Mac[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Pr[\.]*? Man) ([0-9])', r'『85｜\1』 \2', newData)
newData = re.sub('(Ecclus[\.]*?) ([0-9])', r'『87｜\1』 \2', newData)
newData = re.sub('(PssSol[\.]*?) ([0-9])', r'『90｜\1』 \2', newData)
newData = re.sub('(Exodus) ([0-9])', r'『2｜\1』 \2', newData)
newData = re.sub('(Joshua) ([0-9])', r'『6｜\1』 \2', newData)
newData = re.sub('(Judges) ([0-9])', r'『7｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Sam[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Sam[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Sam[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Sa[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Kgs[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Kgs[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Kgs[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Ki[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Chr[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Chr[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Chr[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Ch[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Esther) ([0-9])', r'『17｜\1』 \2', newData)
newData = re.sub('(Psalms) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Eccle[\.]*?) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(Isaiah) ([0-9])', r'『23｜\1』 \2', newData)
newData = re.sub('(Daniel) ([0-9])', r'『27｜\1』 \2', newData)
newData = re.sub('(Haggai) ([0-9])', r'『37｜\1』 \2', newData)
newData = re.sub('(Romans) ([0-9])', r'『45｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Cor[\.]*?) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Cor[\.]*?) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Cor[\.]*?) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Co[\.]*?) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(Ephes[\.]*?) ([0-9])', r'『49｜\1』 \2', newData)
newData = re.sub('(1Thes[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2Thes[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Th[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Tim[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Tim[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Tim[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Ti[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Pet[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(1Peter) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Pet[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Pet[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(2Peter) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Pe[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Pt[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Jhn[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(1[ ]*?John) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Jhn[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Joh[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(I[ ]*?John) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Jhn[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(2[ ]*?John) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Jn[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Jo[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(3[ ]*?Jhn[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(3[ ]*?John) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(Baruch) ([0-9])', r'『70｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Esd[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(1Esdr[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Esd[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Esd[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(2Esdr[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Es[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(EpJer[\.]*?) ([0-9])', r'『79｜\1』 \2', newData)
newData = re.sub('(Judith) ([0-9])', r'『80｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Mac[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(1Macc[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Mac[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Mac[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(2Macc[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(II[ ]*?Ma[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3[ ]*?Mac[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(3Macc[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4[ ]*?Mac[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(4Macc[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(IV[ ]*?Ma[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Sirach) ([0-9])', r'『87｜\1』 \2', newData)
newData = re.sub('(Wisdom) ([0-9])', r'『89｜\1』 \2', newData)
newData = re.sub('(PsSol[\.]*?) ([0-9])', r'『90｜\1』 \2', newData)
newData = re.sub('(Exod[\.]*?) ([0-9])', r'『2｜\1』 \2', newData)
newData = re.sub('(Deut[\.]*?) ([0-9])', r'『5｜\1』 \2', newData)
newData = re.sub('(Josh[\.]*?) ([0-9])', r'『6｜\1』 \2', newData)
newData = re.sub('(Jdgs[\.]*?) ([0-9])', r'『7｜\1』 \2', newData)
newData = re.sub('(Judg[\.]*?) ([0-9])', r'『7｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Sa[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Sm[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(1Sam[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Sa[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Sa[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Sm[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(2Sam[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Ki[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(1Kgs[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(1Kin[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Ki[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Ki[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(2Kgs[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(2Kin[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Ch[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(1Chr[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Ch[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Ch[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(2Chr[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Esth[\.]*?) ([0-9])', r'『17｜\1』 \2', newData)
newData = re.sub('(Psalm) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Pslm[\.]*?) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Prov[\.]*?) ([0-9])', r'『20｜\1』 \2', newData)
newData = re.sub('(Eccl[\.]*?) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(Cant[\.]*?) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(Ezek[\.]*?) ([0-9])', r'『26｜\1』 \2', newData)
newData = re.sub('(Hosea) ([0-9])', r'『28｜\1』 \2', newData)
newData = re.sub('(Obad[\.]*?) ([0-9])', r'『31｜\1』 \2', newData)
newData = re.sub('(Jonah) ([0-9])', r'『32｜\1』 \2', newData)
newData = re.sub('(Micah) ([0-9])', r'『33｜\1』 \2', newData)
newData = re.sub('(Nahum) ([0-9])', r'『34｜\1』 \2', newData)
newData = re.sub('(Zeph[\.]*?) ([0-9])', r'『36｜\1』 \2', newData)
newData = re.sub('(Zech[\.]*?) ([0-9])', r'『38｜\1』 \2', newData)
newData = re.sub('(Matt[\.]*?) ([0-9])', r'『40｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Co[\.]*?) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(1Cor[\.]*?) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Co[\.]*?) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Co[\.]*?) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(2Cor[\.]*?) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(Phil[\.]*?) ([0-9])', r'『50｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Th[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Th[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Th[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Ti[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(1Tim[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Ti[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Ti[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(2Tim[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(Titus) ([0-9])', r'『56｜\1』 \2', newData)
newData = re.sub('(Phlm[\.]*?) ([0-9])', r'『57｜\1』 \2', newData)
newData = re.sub('(James) ([0-9])', r'『59｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Pe[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Pt[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(1Pet[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Pe[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Pt[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Pe[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Pt[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(2Pet[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(1[ ]*?Jn[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(1Jhn[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(1Joh[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(1John) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Jn[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Jo[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(2[ ]*?Jn[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(2Jhn[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(2Joh[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(2John) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(3[ ]*?Jn[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(3Jhn[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(3Joh[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(3John) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(1Esd[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Es[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(2Esd[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(Jdth[\.]*?) ([0-9])', r'『80｜\1』 \2', newData)
newData = re.sub('(1Mac[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(I[ ]*?Ma[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2Mac[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3Mac[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4Mac[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Tobit) ([0-9])', r'『88｜\1』 \2', newData)
newData = re.sub('(Laod[\.]*?) ([0-9])', r'『92｜\1』 \2', newData)
newData = re.sub('(Gen[\.]*?) ([0-9])', r'『1｜\1』 \2', newData)
newData = re.sub('(Exo[\.]*?) ([0-9])', r'『2｜\1』 \2', newData)
newData = re.sub('(Lev[\.]*?) ([0-9])', r'『3｜\1』 \2', newData)
newData = re.sub('(Num[\.]*?) ([0-9])', r'『4｜\1』 \2', newData)
newData = re.sub('(Jos[\.]*?) ([0-9])', r'『6｜\1』 \2', newData)
newData = re.sub('(Jsh[\.]*?) ([0-9])', r'『6｜\1』 \2', newData)
newData = re.sub('(Jdg[\.]*?) ([0-9])', r'『7｜\1』 \2', newData)
newData = re.sub('(Rth[\.]*?) ([0-9])', r'『8｜\1』 \2', newData)
newData = re.sub('(Ruth) ([0-9])', r'『8｜\1』 \2', newData)
newData = re.sub('(1[ ]*?S[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(1Sa[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(2[ ]*?S[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(2Sa[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(1Ki[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2Ki[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(1Ch[\.]*?) ([0-9])', r'『13｜\1』 \2', newData)
newData = re.sub('(2Ch[\.]*?) ([0-9])', r'『14｜\1』 \2', newData)
newData = re.sub('(Ezr[\.]*?) ([0-9])', r'『15｜\1』 \2', newData)
newData = re.sub('(Ezra) ([0-9])', r'『15｜\1』 \2', newData)
newData = re.sub('(Neh[\.]*?) ([0-9])', r'『16｜\1』 \2', newData)
newData = re.sub('(Est[\.]*?) ([0-9])', r'『17｜\1』 \2', newData)
newData = re.sub('(Psa[\.]*?) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Psm[\.]*?) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Pss[\.]*?) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Pro[\.]*?) ([0-9])', r'『20｜\1』 \2', newData)
newData = re.sub('(Prv[\.]*?) ([0-9])', r'『20｜\1』 \2', newData)
newData = re.sub('(Ecc[\.]*?) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(Qoh[\.]*?) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(SOS[\.]*?) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(Song) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(Isa[\.]*?) ([0-9])', r'『23｜\1』 \2', newData)
newData = re.sub('(Jer[\.]*?) ([0-9])', r'『24｜\1』 \2', newData)
newData = re.sub('(Lam[\.]*?) ([0-9])', r'『25｜\1』 \2', newData)
newData = re.sub('(Eze[\.]*?) ([0-9])', r'『26｜\1』 \2', newData)
newData = re.sub('(Ezk[\.]*?) ([0-9])', r'『26｜\1』 \2', newData)
newData = re.sub('(Dan[\.]*?) ([0-9])', r'『27｜\1』 \2', newData)
newData = re.sub('(Hos[\.]*?) ([0-9])', r'『28｜\1』 \2', newData)
newData = re.sub('(Joe[\.]*?) ([0-9])', r'『29｜\1』 \2', newData)
newData = re.sub('(Joel) ([0-9])', r'『29｜\1』 \2', newData)
newData = re.sub('(Amo[\.]*?) ([0-9])', r'『30｜\1』 \2', newData)
newData = re.sub('(Amos) ([0-9])', r'『30｜\1』 \2', newData)
newData = re.sub('(Oba[\.]*?) ([0-9])', r'『31｜\1』 \2', newData)
newData = re.sub('(Jnh[\.]*?) ([0-9])', r'『32｜\1』 \2', newData)
newData = re.sub('(Jon[\.]*?) ([0-9])', r'『32｜\1』 \2', newData)
newData = re.sub('(Mic[\.]*?) ([0-9])', r'『33｜\1』 \2', newData)
newData = re.sub('(Nah[\.]*?) ([0-9])', r'『34｜\1』 \2', newData)
newData = re.sub('(Hab[\.]*?) ([0-9])', r'『35｜\1』 \2', newData)
newData = re.sub('(Zep[\.]*?) ([0-9])', r'『36｜\1』 \2', newData)
newData = re.sub('(Hag[\.]*?) ([0-9])', r'『37｜\1』 \2', newData)
newData = re.sub('(Zec[\.]*?) ([0-9])', r'『38｜\1』 \2', newData)
newData = re.sub('(Mal[\.]*?) ([0-9])', r'『39｜\1』 \2', newData)
newData = re.sub('(Mat[\.]*?) ([0-9])', r'『40｜\1』 \2', newData)
newData = re.sub('(Mar[\.]*?) ([0-9])', r'『41｜\1』 \2', newData)
newData = re.sub('(Mark) ([0-9])', r'『41｜\1』 \2', newData)
newData = re.sub('(Mrk[\.]*?) ([0-9])', r'『41｜\1』 \2', newData)
newData = re.sub('(Luk[\.]*?) ([0-9])', r'『42｜\1』 \2', newData)
newData = re.sub('(Luke) ([0-9])', r'『42｜\1』 \2', newData)
newData = re.sub('(Act[\.]*?) ([0-9])', r'『44｜\1』 \2', newData)
newData = re.sub('(Acts) ([0-9])', r'『44｜\1』 \2', newData)
newData = re.sub('(Rom[\.]*?) ([0-9])', r'『45｜\1』 \2', newData)
newData = re.sub('(1Co[\.]*?) ([0-9])', r'『46｜\1』 \2', newData)
newData = re.sub('(2Co[\.]*?) ([0-9])', r'『47｜\1』 \2', newData)
newData = re.sub('(Gal[\.]*?) ([0-9])', r'『48｜\1』 \2', newData)
newData = re.sub('(Eph[\.]*?) ([0-9])', r'『49｜\1』 \2', newData)
newData = re.sub('(Php[\.]*?) ([0-9])', r'『50｜\1』 \2', newData)
newData = re.sub('(Col[\.]*?) ([0-9])', r'『51｜\1』 \2', newData)
newData = re.sub('(1Th[\.]*?) ([0-9])', r'『52｜\1』 \2', newData)
newData = re.sub('(2Th[\.]*?) ([0-9])', r'『53｜\1』 \2', newData)
newData = re.sub('(1Ti[\.]*?) ([0-9])', r'『54｜\1』 \2', newData)
newData = re.sub('(2Ti[\.]*?) ([0-9])', r'『55｜\1』 \2', newData)
newData = re.sub('(Tit[\.]*?) ([0-9])', r'『56｜\1』 \2', newData)
newData = re.sub('(Phm[\.]*?) ([0-9])', r'『57｜\1』 \2', newData)
newData = re.sub('(Heb[\.]*?) ([0-9])', r'『58｜\1』 \2', newData)
newData = re.sub('(Jam[\.]*?) ([0-9])', r'『59｜\1』 \2', newData)
newData = re.sub('(Jas[\.]*?) ([0-9])', r'『59｜\1』 \2', newData)
newData = re.sub('(1[ ]*?P[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(1Pe[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(1Pt[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(2[ ]*?P[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(2Pe[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(2Pt[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(1[ ]*?J[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(1Jn[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(1Jo[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(2[ ]*?J[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(2Jn[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(2Jo[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(3[ ]*?J[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(3Jn[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(3Jo[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(Jud[\.]*?) ([0-9])', r'『65｜\1』 \2', newData)
newData = re.sub('(Jude) ([0-9])', r'『65｜\1』 \2', newData)
newData = re.sub('(Rev[\.]*?) ([0-9])', r'『66｜\1』 \2', newData)
newData = re.sub('(Bar[\.]*?) ([0-9])', r'『70｜\1』 \2', newData)
newData = re.sub('(Bel[\.]*?) ([0-9])', r'『73｜\1』 \2', newData)
newData = re.sub('(Sus[\.]*?) ([0-9])', r'『75｜\1』 \2', newData)
newData = re.sub('(1Es[\.]*?) ([0-9])', r'『76｜\1』 \2', newData)
newData = re.sub('(2Es[\.]*?) ([0-9])', r'『77｜\1』 \2', newData)
newData = re.sub('(AEs[\.]*?) ([0-9])', r'『78｜\1』 \2', newData)
newData = re.sub('(LJe[\.]*?) ([0-9])', r'『79｜\1』 \2', newData)
newData = re.sub('(Jdt[\.]*?) ([0-9])', r'『80｜\1』 \2', newData)
newData = re.sub('(Jth[\.]*?) ([0-9])', r'『80｜\1』 \2', newData)
newData = re.sub('(1Ma[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2Ma[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3Ma[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4Ma[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(PMa[\.]*?) ([0-9])', r'『85｜\1』 \2', newData)
newData = re.sub('(Sir[\.]*?) ([0-9])', r'『87｜\1』 \2', newData)
newData = re.sub('(Tob[\.]*?) ([0-9])', r'『88｜\1』 \2', newData)
newData = re.sub('(Wis[\.]*?) ([0-9])', r'『89｜\1』 \2', newData)
newData = re.sub('(Ode[\.]*?) ([0-9])', r'『91｜\1』 \2', newData)
newData = re.sub('(Odes) ([0-9])', r'『91｜\1』 \2', newData)
newData = re.sub('(Ge[\.]*?) ([0-9])', r'『1｜\1』 \2', newData)
newData = re.sub('(Gn[\.]*?) ([0-9])', r'『1｜\1』 \2', newData)
newData = re.sub('(Ex[\.]*?) ([0-9])', r'『2｜\1』 \2', newData)
newData = re.sub('(Le[\.]*?) ([0-9])', r'『3｜\1』 \2', newData)
newData = re.sub('(Lv[\.]*?) ([0-9])', r'『3｜\1』 \2', newData)
newData = re.sub('(Nb[\.]*?) ([0-9])', r'『4｜\1』 \2', newData)
newData = re.sub('(Nm[\.]*?) ([0-9])', r'『4｜\1』 \2', newData)
newData = re.sub('(Nu[\.]*?) ([0-9])', r'『4｜\1』 \2', newData)
newData = re.sub('(De[\.]*?) ([0-9])', r'『5｜\1』 \2', newData)
newData = re.sub('(Dt[\.]*?) ([0-9])', r'『5｜\1』 \2', newData)
newData = re.sub('(Jg[\.]*?) ([0-9])', r'『7｜\1』 \2', newData)
newData = re.sub('(Ru[\.]*?) ([0-9])', r'『8｜\1』 \2', newData)
newData = re.sub('(1S[\.]*?) ([0-9])', r'『9｜\1』 \2', newData)
newData = re.sub('(2S[\.]*?) ([0-9])', r'『10｜\1』 \2', newData)
newData = re.sub('(1K[\.]*?) ([0-9])', r'『11｜\1』 \2', newData)
newData = re.sub('(2K[\.]*?) ([0-9])', r'『12｜\1』 \2', newData)
newData = re.sub('(Ez[\.]*?) ([0-9])', r'『15｜\1』 \2', newData)
newData = re.sub('(Ne[\.]*?) ([0-9])', r'『16｜\1』 \2', newData)
newData = re.sub('(Es[\.]*?) ([0-9])', r'『17｜\1』 \2', newData)
newData = re.sub('(Jb[\.]*?) ([0-9])', r'『18｜\1』 \2', newData)
newData = re.sub('(Job) ([0-9])', r'『18｜\1』 \2', newData)
newData = re.sub('(Ps[\.]*?) ([0-9])', r'『19｜\1』 \2', newData)
newData = re.sub('(Pr[\.]*?) ([0-9])', r'『20｜\1』 \2', newData)
newData = re.sub('(Ec[\.]*?) ([0-9])', r'『21｜\1』 \2', newData)
newData = re.sub('(So[\.]*?) ([0-9])', r'『22｜\1』 \2', newData)
newData = re.sub('(Is[\.]*?) ([0-9])', r'『23｜\1』 \2', newData)
newData = re.sub('(Je[\.]*?) ([0-9])', r'『24｜\1』 \2', newData)
newData = re.sub('(Jr[\.]*?) ([0-9])', r'『24｜\1』 \2', newData)
newData = re.sub('(La[\.]*?) ([0-9])', r'『25｜\1』 \2', newData)
newData = re.sub('(Da[\.]*?) ([0-9])', r'『27｜\1』 \2', newData)
newData = re.sub('(Dn[\.]*?) ([0-9])', r'『27｜\1』 \2', newData)
newData = re.sub('(Ho[\.]*?) ([0-9])', r'『28｜\1』 \2', newData)
newData = re.sub('(Jl[\.]*?) ([0-9])', r'『29｜\1』 \2', newData)
newData = re.sub('(Am[\.]*?) ([0-9])', r'『30｜\1』 \2', newData)
newData = re.sub('(Ob[\.]*?) ([0-9])', r'『31｜\1』 \2', newData)
newData = re.sub('(Mc[\.]*?) ([0-9])', r'『33｜\1』 \2', newData)
newData = re.sub('(Na[\.]*?) ([0-9])', r'『34｜\1』 \2', newData)
newData = re.sub('(Hb[\.]*?) ([0-9])', r'『35｜\1』 \2', newData)
newData = re.sub('(Zp[\.]*?) ([0-9])', r'『36｜\1』 \2', newData)
newData = re.sub('(Hg[\.]*?) ([0-9])', r'『37｜\1』 \2', newData)
newData = re.sub('(Zc[\.]*?) ([0-9])', r'『38｜\1』 \2', newData)
newData = re.sub('(Ml[\.]*?) ([0-9])', r'『39｜\1』 \2', newData)
newData = re.sub('(Mt[\.]*?) ([0-9])', r'『40｜\1』 \2', newData)
newData = re.sub('(Mk[\.]*?) ([0-9])', r'『41｜\1』 \2', newData)
newData = re.sub('(Mr[\.]*?) ([0-9])', r'『41｜\1』 \2', newData)
newData = re.sub('(Lk[\.]*?) ([0-9])', r'『42｜\1』 \2', newData)
newData = re.sub('(Ac[\.]*?) ([0-9])', r'『44｜\1』 \2', newData)
newData = re.sub('(Rm[\.]*?) ([0-9])', r'『45｜\1』 \2', newData)
newData = re.sub('(Ro[\.]*?) ([0-9])', r'『45｜\1』 \2', newData)
newData = re.sub('(Ga[\.]*?) ([0-9])', r'『48｜\1』 \2', newData)
newData = re.sub('(Pp[\.]*?) ([0-9])', r'『50｜\1』 \2', newData)
newData = re.sub('(Co[\.]*?) ([0-9])', r'『51｜\1』 \2', newData)
newData = re.sub('(ti[\.]*?) ([0-9])', r'『56｜\1』 \2', newData)
newData = re.sub('(Pm[\.]*?) ([0-9])', r'『57｜\1』 \2', newData)
newData = re.sub('(Jm[\.]*?) ([0-9])', r'『59｜\1』 \2', newData)
newData = re.sub('(1P[\.]*?) ([0-9])', r'『60｜\1』 \2', newData)
newData = re.sub('(2P[\.]*?) ([0-9])', r'『61｜\1』 \2', newData)
newData = re.sub('(1J[\.]*?) ([0-9])', r'『62｜\1』 \2', newData)
newData = re.sub('(2J[\.]*?) ([0-9])', r'『63｜\1』 \2', newData)
newData = re.sub('(3J[\.]*?) ([0-9])', r'『64｜\1』 \2', newData)
newData = re.sub('(Jd[\.]*?) ([0-9])', r'『65｜\1』 \2', newData)
newData = re.sub('(Re[\.]*?) ([0-9])', r'『66｜\1』 \2', newData)
newData = re.sub('(1M[\.]*?) ([0-9])', r'『81｜\1』 \2', newData)
newData = re.sub('(2M[\.]*?) ([0-9])', r'『82｜\1』 \2', newData)
newData = re.sub('(3M[\.]*?) ([0-9])', r'『83｜\1』 \2', newData)
newData = re.sub('(4M[\.]*?) ([0-9])', r'『84｜\1』 \2', newData)
newData = re.sub('(Tb[\.]*?) ([0-9])', r'『88｜\1』 \2', newData)
newData = re.sub('(Ws[\.]*?) ([0-9])', r'『89｜\1』 \2', newData)
# Book of John placed at the end, to avoid being tagged before references of 1,2,3 John
newData = re.sub('(Jhn[\.]*?) ([0-9])', r'『43｜\1』 \2', newData)
newData = re.sub('(Joh[\.]*?) ([0-9])', r'『43｜\1』 \2', newData)
newData = re.sub('(John) ([0-9])', r'『43｜\1』 \2', newData)
newData = re.sub('(Jn[\.]*?) ([0-9])', r'『43｜\1』 \2', newData)

# newData = re.sub('『0', '『', newData)

# dealt with common patterns:
# e.g. Book 1:1-2:1; 3:2-4, 5; Jude 1
newData = re.sub('『([0-9]+?)｜([^\n『』]*?)』 ([0-9]+?):([0-9]+?)([^0-9])', r'<ref onclick="bcv(\1,\3,\4)">\2 \3:\4</ref>\5', newData)
newData = re.sub('『([0-9]+?)｜([^\n『』]*?)』 ([0-9]+?)([^0-9])', r'<ref onclick="bcv(\1,\3,)">\2 \3</ref>\4', newData)
newData = fixEmptyVerse(newData)

# check if verses following tagged references
p = re.compile('</ref>[,-;][ ]*?[0-9]', flags=re.M)
s = p.search(newData)
while s:
    newData = re.sub('<ref onclick="bcv\(([0-9]+?),([0-9]+?),([0-9]+?)\)">(.*?)</ref>([,-;][ ]*?)([0-9]+?):([0-9]+?)([^0-9])', r'<ref onclick="bcv(\1,\2,\3)">\4</ref>\5<ref onclick="bcv(\1,\6,\7)">\6:\7</ref>\8', newData)
    newData = re.sub('<ref onclick="bcv\(([0-9]+?),([0-9]+?),([0-9]+?)\)">([^＊].*?)</ref>([,-;][ ]*?)([0-9]+?)([^:0-9])', r'<ref onclick="bcv(\1,\2,\3)">\4</ref>\5<ref onclick="bcv(\1,\2,\6)">\6</ref>\7', newData)
    newData = re.sub('<ref onclick="bcv\(([0-9]+?),([0-9]+?),([0-9]+?)\)">(＊.*?)</ref>([,-;][ ]*?)([0-9]+?)([^:0-9])', r'<ref onclick="bcv(\1,\2,\3)">\4</ref>\5<ref onclick="bcv(\1,\6,1)">＊\6</ref>\7', newData)
    s = p.search(newData)

# clear special markers
newData = re.sub('『[0-9]+?|([^\n『』]*?)』', r'\1', newData)
newData = re.sub('(<ref onclick="bcv\([0-9]+?,[0-9]+?,[0-9]+?\)">)＊', r'\1', newData)

# ask if standardising abbreviations and reference format
newData = standardReference(newData, input("Do you want to standardise all references [YES/NO]? "))

# close file
f = open(outputFile,'w')
f.write(newData)
f.close()

print("All DONE! Verse references are tagged and saved in file '"+outputFile+"'")